# Upload artifacts: https://github.com/actions/upload-artifact
# Download artifacts: https://github.com/actions/download-artifact
# Cache: https://github.com/actions/cache

name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
        # Caching reusable files so reduces the workflow execution time on dealing with same. For specific scenario related check the official page
        # On first run with cache dependencies it will take the general timing. On further jobs and futher sub-sequent runs it will take the Cached dependencies
        # On every version update the Cache gets resets to another hash version and will be used on further runs of the updated cache
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }} # Get all the information of the file and make into a hash so which eventually used to somewhere we require
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    # Accessing the outputs to use in other jobs or accessible to other jobs
    outputs: # Overall output from the job
      script-file: ${{ steps.publish.outputs.script-file }} # user choice for naming
      # After outputs.<name> the name should be match in both the places. Here and at the step
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Publish js file name
        id: publish # giving id to access uniquely for the steps and accessing output values from the id
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';' # Find the javascript file
        # 'script-file={}' >> #GITHUB_OUTPUT is a step output not the overall output
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist-name # user choice for naming
          path: dist
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v7 # Downloads the artifacts uploaded by the previous version
        with:
          name: dist-name # Same name for upload artifacts should be used here. And multiple artifacts can't downloaded or used at once
      - name: Output contents
        run: ls
      - name: Output file name
        run: echo "${{ needs.build.outputs.script-file }}" # using needs we can get the output of particular data from other jobs
      - name: Deploy
        run: echo "Deploying..."
