# Workflow Syntax: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
# Skip workflows: https://docs.github.com/en/actions/how-tos/manage-workflow-runs/skip-workflow-runs?versionId=free-pro-team%40latest&productId=actions&restPage=reference%2Cworkflows-and-actions%2Cworkflow-syntax

name: Events Demo 1
on:
  pull_request:
    types: # opened # accepts multiple values too. Ex: Array or list type declaration
      - opened
    # Note: Forked repositories pull request on first time won't run automatically. Real owner should give run access approval so subsequent pull requests run automatically
    branches:
       - main
       - dev
       - 'dev-*'
       - 'feat/**'
  workflow_dispatch: # even though there are no arguments we should still declare in this way
  push:
    branches:
       - main
       - dev
       - 'dev-*' # covers dev-new, dev-this etc
       - 'feat/**' # covers feat/new, feat/new/this etc
    paths-ignore: # runs the workflow when the following branch and following path/files are not having any changes
      - '.github/workflow/*' # outside this any change is made the workflow runs if one file is changed from specified it won't run
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."