# Events and Triggers: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
# Actions: https://github.com/actions/checkout
# Actions - Marketplace: https://github.com/marketplace/actions/checkout
# Runners(machines): https://github.com/actions/runner-images?tab=readme-ov-file
# Runners Configuration: https://github.com/actions/runner?tab=readme-ov-file

name: "Test Project 01 Section 03"
on: push # Events and Triggers
jobs:
  test:
    runs-on: ubuntu-latest # machine that we would like to use to run the code
    steps:
      # Get the code downloaded to the machine which we mentioned
      - name: Get Code
        uses: actions/checkout@v6 # Actions - Checkout
      - name: Install NodeJS # ubuntu latest has nodejs but we can still configure it
        uses: actions/setup-node@v3
        with:
          node-version: 24
      # Install required dependencies
      - name: Install dependencies
        run: npm ci
      # Run the tests
      - name: Run tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ...."